### ISSUE TITLE
EmbeddedFileProvider cannot load embedded _ViewStart and _ViewImports

### ISSUE THREAD

**Issue by mnguyen284** [aspnet/FileSystem#129]
In GetFileInfo function, we replaced '/' with '.' to create resourcePath.

```
public IFileInfo GetFileInfo(string subpath)
{
    ...
    string resourcePath = _baseNamespace + subpath.Replace('/', '.');
    ...
}
```

However, when requesting _ViewStart and _ViewImports subpath comes with '\' instead of '/' causing resourcePath to be incorrect.

My suggestion is to replace both '/' and '\' with '.'.

**Comment by Eilon** [comment]
@pranavkm do you know if this is more of an MVC issue or a FileSystem issue?

**Comment by pranavkm** [comment]
Let me run this by @loudej to see what he thinks about this. It's fine for the EmbeddedFileSystem to only support `/` path separators - the problem is that it doesn't work well with paths generated using `Path.Combine` on windows. 

On Mvc's end we can do a better job and construct these paths using forward slashes. It's on @rynowak's radar since Path.Combine allocates too much and we don't need to have it behave the way it does. We were waiting to have a chat with @loudej to figure out if we want to fix it piecemeal or revisit the caching and allocation story for Razor view engines in general.
