### ISSUE TITLE
Revisit how physical file watcher handles events

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/FileSystem#189]
We did a quick fix for https://github.com/aspnet/FileSystem/issues/187 for RC2 but we should revisit the solution for RTM. Aka, it's bad that we're swallowing exceptions and should investigate other alternatives.

**Comment by natemcmaster** [comment]
@muratg I recommend we close as wont-fix. The result of this bug is that a file watch token may not always fire for renamed events when the rename caused the directory structure to change permissions or exceed the MAX_PATH length.

I've looked at the changes made in #187, and there aren't good alternatives. In this specific case, it is the System.IO API that is throws when there is an issue traversing the directory structure. There aren't any non-throwing System.IO apis we can use to achieve the same result.

**Comment by muratg** [comment]
👍
