### ISSUE TITLE
[Question] Write support for FileProviders

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/FileSystem#200]
In a web application, saving user uploaded files is a general task. It seems that currently the file provider only supported reading operation for files, that means if I want to save a file, I must use low-level operations, e.g. using File.Create or other API to write a binary stream into the file system. 

Actually, the high level application should only care about 2 things: Save a stream into a specified virtual path, or read a steam from one path. Thus I'm wondering if the file provider can add the support for file wrting,  under such circumstance, all file related read/write operations can be delegated with a FileProvider. It may greatly enhances the FIleSystem abstraction, e.g. All files may be writen to SQL Server databases, and all reading action will lead to a database fetching. File datas are merged in a centred places instead of seperated items. Besides, no code in the high level application must be rewriten when low-level storage method is modified.

Some FileProviders may have difficulty for writing, e.g. the content of `EmbeddedFileProvider` can not be changed, thus the FileProvider may raise an exception when writing operation is triggered.

If there's already an absraction manner for file writing, could you please demonstrate the API usage? Thanks a lot~

**Comment by Kation** [comment]
Yeah, I think this is useful too.
We can implement some file provider base on ftp and webapi etc.

**Comment by thomaslevesque** [comment]
I was so glad to find this library... and so disappointed when I realized it didn't handle write scenarios!
Adding support for this should be as simple as adding a `CreateWriteStream` method on `IFileInfo` (well maybe it would need a few parameters to specify things like FileMode, FileAccess, FIleShare etc)

**Comment by SebastianStehle** [comment]
Would be super helpful for me as well.

**Comment by dazinator** [comment]
Not sold on this, and I'll try and explain why.. The nice thing about having IFileProvider essentially provide only "read" functionality is this:

You can combine multiple `IFileProviders` into a composite. This lets you read a file without worrying about where its read from.

For example, you can combine OneDrive File Provider, with a GoogleDriveFileProvider into a composite.
When you then retrieve a file - you don't care whether its coming from OneDrive or Google Drive or any of the other sources.

This is perfect for building a virtual file system (for read purposes).

However if each IFileProvider also had write() functionality - when using a CompositeFileProvider - and wanting to create a new file at "/foo.txt" - how do where know where to write the file too? GoogleDrive or OneDrive?

I think I am going to try and address this by creating a library that gives a virtual file system, by using a Composite IFileProvider to provide its read access, and using some other form of abstraction for it's write access.

For example, if you had a virtual file system that had the composite file provider to read files from google drive and one drive. But it also provided a write API for creating files. It could use System.IO to physically write files locally to some area on disk. It could then include a PhysicalFileProvider into the composite IFileProviders so that whenever you write a new file, the file shows up for each operations, GetDirectoryContents etc. The fact that the virtual file system is using System.IO behind the scenes can be an implementation detail, and could be swapped to say, write files to a database.

**Comment by dazinator** [comment]
One other thing to watch out for,
If you attempt to write to a file, that is being actively read from (many of the files provided by IFileProvider are served up) the writes will fail as the file is in use. This makes attempting to modify files that are provided by an IFileProvider a potential pain if they are constantly being accessed. However that may be a sign that you need to use caching or something else - just mentioning it as an aside really,

**Comment by dazinator** [comment]
You can find more here: https://github.com/dazinator/DotNet.Cabinet/

**Comment by SebastianStehle** [comment]
I am not sure if the implementation of the composite file provider is really clever at the moment. I see a problem:

1. File paths are not unique anymore. Two files could have the same path and it is defined by the order of how you register the file providers which files will be used. This might become when you create a new file. Before you got it from provider B but after you added a file with the same name to provider A (e.g. with the explorer or using a azure blob management software) you get it from A.

2. Performance decreases with the number of providers you have. And because we talk about IO which is usually very limited it can become really slow. And even expensive if you use a cloud service as a provider.

3. I haven't seen this concept in a file system before. In Windows you have partitions with letters and in linux you use mounting to combine system file providers to a file system. Therefore it is confusing.

In my opinion it would make sense to build the compositeprovider like this:

     var composite = 
		new CompositeFileProvider(
			new FileSystemMapping {
				["hotel-images"] = new AzureFileProvider(),
				["scripts"] = new PhysicalFileProvider("wwwroot/scripts"),
				["styles"] = new PhysicalFileProvider("wwwroot/styles")
			});

Or an even more advanced configuration. This is also how you would make your decision process. You say "Lets store the hotel-images in azure, because we need CDN support for it and we they are so big and ... "

**Comment by dazinator** [comment]
You can achieve that kind of mapping already. Take a look at the RequestPathFileProvider I made here: https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders

You'd use it like this:

```
var composite = new CompositeFileProvider(new RequestPathFileProvider("hotel-images", new AzureFileProvider()), new RequestPathFileProvider("scripts", new PhysicalFileProvider("wwwroot/scripts")));
```

**Comment by dazinator** [comment]
In addition, your point here:

> File paths are not unique anymore. Two files could have the same path and it is defined by the order of how you register the file providers which files will be used. This might become when you create a new file. Before you got it from provider B but after you added a file with the same name to provider A (e.g. with the explorer or using a azure blob management software) you get it from A.

I am actually deliberately exploiting this ability here: https://github.com/dazinator/DotNet.Cabinet/ 
It basically allows for the concept of have different layers of files, where for example, a system layer of files can be "overridden" by another layer, but not replaced. In a modular system, this allows for example Module A, to have access to a system layer of files, but override any of them with its own version of the file, without impacting Modules B, C, D which could all do the same. You can get an interesting effect this way. It also provides for isolation.

For example, suppose your application is a CMS, consisting of different modules. You can layer the file system so that system files are at one layer, and modules can override system files, with their own layer. For example, the system provides "/module/default.css", and then Module A can access "/module/default.css"  - i.e the system version of the file, but it could also override that version with its own "/module.default.css" - without impacting other modules like Module B which still resolves to the system version of module.css". I agree that this is complicated, but I think it is also a useful effect for this type of situation.

**Comment by SebastianStehle** [comment]
Good to know that it is already possible. I see, that there are definitely some scenarios where it makes sense, but these scenarios are rare and it is just a configuration of how to register them.

See the following example:


	FileSystemBuilder.New()
		.AddReadOnly("scripts", new PhysicalFileProvider("wwwroot/scripts")),
		.AddReadOnly("styles", new PhysicalFileProvider("wwwroot/styles")),
		.AddWriteable("user-images", new AzureFileProvider()),
		.AddReadOnly("modules",
			FileSystemBuilder.New()
				.AddMerged("module1",
					new PhysicalFileProvider("wwwroot/moduledefaults"),
					new ResourceFileProvider(module1Assembly)),
			FileSystemBuilder.New()
				.AddMerged("module1",
					new PhysicalFileProvider("wwwroot/moduledefaults"),
					new ResourceFileProvider(module1Assembly)))
		.Build();

 Merging file providers could mean, that it is always read only, if you do not declare a write target.

=> Even with the current system you can get a lot of problems. E.g. bad performance, high costs and maintenance issues, if you do it the wrong way. If you merge all files from all plugins/modules in a cms to a single path then you can get a lot of issues. For me the Write features do not make it worse. It would be nice to have a better configuration system that prevents you from doing stupid things. It would be nice to handle the most important use case with this file provider here. I think it is user uploads. So there is probably no need for renaming and so on. It sucks that I have to build another abstraction over files :(

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
