### ISSUE TITLE
Can we defer creation of the PhysicalFileWatcher in PhysicalFileProvider

### ISSUE THREAD

**Issue by rynowak** [aspnet/FileSystem#223]
`PhysicalFileProvider` always creates a file watcher when it's created. I'm wondering if we need this or if we could just defer the work until it's needed.

This happens on the hosting startup path so it's critical path for startup. I don't have any evidence yet that it's a significant perf factor, it just seems like work we could avoid.

**Comment by muratg** [comment]
@rynowak did you end up having any measurements for this code path?

**Comment by rynowak** [comment]
no update on this from me, I haven't looked at it again

**Comment by pranavkm** [comment]
Not entirely relevant since this was done in a non-hosted application, but here's a profile from when I was working on MvcPrecompilation:

![image](https://cloud.githubusercontent.com/assets/174281/18803422/bc513590-81a4-11e6-9be3-ad8edc9bd8ba.png)

That said, it should be a pretty small change to make the instantiation deferred.

**Comment by muratg** [comment]
Impact seems to be low enough. Even if the change is small, it would still be churn with potential issues we haven't thought of. 

Backlogging for now, but let me know if you guys feel like this is important enough and we should bring it back in 1.2.

**Comment by dazinator** [comment]
@muratg2 - here is seemingly a knock on effect if this issue - please see #282

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2552
