### ISSUE TITLE
Implement CombinedFileSystemProvider

### ISSUE THREAD

**Issue by glennc** [aspnet/FileSystem#49]
The CombinedFileSystemProvider would accept multiple FileSystemProviders and return files if they exist in one of them.

**Comment by kichalla** [comment]
@muratg Fixing this issue can help in fixing https://github.com/aspnet/Diagnostics/issues/157 where razor files could be(as MVC gives this option) coming from physical or embedded resources

cc @davidfowl

**Comment by kichalla** [comment]
Actually ignore my previous comment, the fix for aspnet/Diagnostics#157 is not dependent on fixing this issue...but from an end user perspective would be nice to have..

**Comment by pranavkm** [comment]
Need this for https://github.com/aspnet/Mvc/issues/2551

**Comment by glennc** [comment]
This is backlog for now. If it is definitely needed for MVC then come talk to us.

**Comment by mgrosperrin** [comment]
Hi,
I'm really interested by this CombinedFileProvider.
Currently, I have my own implementation, but have to duplicate the not found file and directory (from the Microsoft.AspNet.FileProviders.Sources project).
Can I submit you a PR with this new file provider or is already someone working on it ?

**Comment by pranavkm** [comment]
PR sounds great. I tried playing with this at one point and sort of dropped it because it was missing some design -

1. For GetFileInfo - does it keep querying until it finds a file?
2. For GetDirectoryContents - does it combine the results of multiple `IFileProvider` instances?

These might not be an issue if individual IFileProviders were isolated in separate hives (had to have distinct roots) but that didn't work for the scenarios we were trying to use it in Mvc.

**Comment by mgrosperrin** [comment]
Hi,
OK for merging the content of multiple directories.
When I do this, should I consider that the Name property (of IFileInfo) is unique for a directory (ie when I have a file with a given name from a directory, I skip all files with the same name in the later directories)?

**Comment by MartinJohns** [comment]
I was thinking a bit about this issue and here are my two cents:

1. `GetFileInfo`: This should iterate over all provided `IFileProvider` and return the first result where `Exists` is true. If there was no existing file found, then a `FileNotFound` class should be returned, as it is happening with all providers currently. This potentially leads to a lot of unnecessary garbage, because each provider will always instantiate a `FileNotFound` class which is thrown away immediately.

2. `GetDirectoryContents`: This should merge the contents of all provided `IFileProvider`. On duplicate entries (uniqueness on the `Name` property) it should take the first entry it found (again by the order of provided file providers).

3. `Watch`: The biggest trouble I see is with this method that returns the `IChangeToken` which notifies about changes. I think simply not providing this functionality is a poor cheap way out and would not help with some requirements. I think this should combine the changes of all file providers. This would allow nifty things like having an embedded version, which can be overridden by a physical file without restarting the application. I would even think further and say that a change notification from provider B should not be propagated, when the actual file was returned by provider A (since A takes priority and it did not change) - but that would seem impossible the given interface, and changes in such an elementary interface are unlikely at RC1.

**Comment by muratg** [comment]
Thanks, @MartinJohns.  FWIV, RC1 is already released BTW! :)

**Comment by mgrosperrin** [comment]
Hi,
for the `Watch` method, I decided to create a new `IChangeToken` that "merges" all tokens.

The caller will potentially be notified for files that cannot be accessed, but I don't see how to do differently :disappointed:

**Comment by pranavkm** [comment]
@mgrosperrin that sounds fine. Over expiring shouldn't be a problem. The first two bullet points from @MartinJohns sound fine.
