### ISSUE TITLE
Make Matcher easier to test

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/FileSystem#60]
`Matcher` currently is hard to use in other types in a way that makes those types testable, as you can't observe the current state of the `Matcher` (e.g. what patterns are active via properties), you can't mock it (because the members aren't virtual), and you can't substitute the `Matcher` completely without wrapping it which seems like overkill given it's in our codebase.

Perhaps we can make the members virtual, and add some protected properties to be able to see the current pattern lists (include and excludes).

**Comment by davidfowl** [comment]
Can you give an example?

**Comment by troydai** [comment]
@davidfowl Here's my understanding: For @DamianEdwards to unit test a component which uses the `Matcher` is difficult because the `Matcher` is none extensible. Therefore you can't mock it. 

This is a good point. Given that almost or the other components in `FileSystemGlobbing` are mockable, the `Matcher`'s testability looks odd. I believe the solution is to either introduce a `IMatcher` interface.

**Comment by troydai** [comment]
Fixed in ff1f436dc5457f2aa2f520806f23d9356a09b4ac
